CREATE TABLE IF NOT EXISTS DIAGNOSIS(
	DIAGNOSIS_ID INT,
    ICDIOCM VARCHAR(7),
    D_NAME VARCHAR(255),
    FORM_ID INT NOT NULL,
    SERVICE_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (DIAGNOSIS_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID),
    FOREIGN KEY (SERVICE_EMPLOYEE_ID) REFERENCES SERVICE_PROVIDER(SERVICE_EMPLOYEE_ID)
);