CREATE TABLE IF NOT EXISTS EMERGENCY_PHONE_NUMBERS(
	EMERGENCY_ID INT,
    PHONE_NUMBER VARCHAR(25),
    PRIMARY KEY (EMERGENCY_ID, PHONE_NUMBER),
    FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_CONTACT(EMERGENCY_ID)
);