CREATE TABLE IF NOT EXISTS FORM(
    FORM_ID INT,
    F_DATE DATETIME,
    CLERK_ID INT NOT NULL,
    PRIMARY KEY (FORM_ID),
    FOREIGN KEY (CLERK_ID) REFERENCES INTAKE_CLERK(INTAKE_EMPLOYEE_ID)
);