CREATE TABLE IF NOT EXISTS INSURANCE_PROVIDER (
    MEMBER_ID INT,
    POLICY_NUMBER VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    PATIENT_ID INT NOT NULL,
    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);