CREATE TABLE IF NOT EXISTS INTAKE_CLERK(
	INTAKE_EMPLOYEE_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    PAYSCALE DECIMAL(2,2),
    SALARY DECIMAL(2,2),
    DNO INT NOT NULL,
    PRIMARY KEY (INTAKE_EMPLOYEE_ID),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO)
);