CREATE TABLE IF NOT EXISTS INITIAL_ASSESSMENT (
    ASSESSMENT_ID INT,
    HEIGHT VARCHAR(255),
    WEIGHT DECIMAL(2,2),
    BLOOD_PRESSURE VARCHAR(255),
    TEMPERATURE DECIMAL(2,2),
    FORM_ID INT NOT NULL,
    NURSE_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (ASSESSMENT_ID),
    FOREIGN KEY (FORM_ID) REFERENCES FORM(FORM_ID),
    FOREIGN KEY (NURSE_EMPLOYEE_ID) REFERENCES NURSE(NURSE_EMPLOYEE_ID)
);