CREATE TABLE IF NOT EXISTS PATIENT (
    PATIENT_ID INT,
    FNAME VARCHAR(255),
    MNAME VARCHAR(255),
    LNAME VARCHAR(255),
    STREET VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    ZIP INT,
    DOB DATE,
    GUARDIAN_ID INT,
    PRIMARY KEY (PATIENT_ID),
    FOREIGN KEY (GUARDIAN_ID) REFERENCES GUARDIAN(GUARDIAN_ID)
);