CREATE TABLE IF NOT EXISTS PATIENT_PHONE(
	PATIENT_ID INT,
    PHONE_NUMBER VARCHAR(25),
    PRIMARY KEY (PATIENT_ID, PHONE_NUMBER),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);