CREATE TABLE IF NOT EXISTS SYMPTOMS(
	  ASSESSMENT_ID INT,
    SYMPTOM VARCHAR(255),
    PRIMARY KEY (ASSESSMENT_ID, SYMPTOM),
    FOREIGN KEY (ASSESSMENT_ID) REFERENCES INITIAL_ASSESSMENT(ASSESSMENT_ID)
);