CREATE TABLE IF NOT EXISTS TREATMENT (
    TREATMENT_ID INT,
    ICDLOPCS VARCHAR(7),
    TREATMENT_NAME VARCHAR(255),
    COST DECIMAL(2,2),
    PATIENT_ID INT NOT NULL,
    PRIMARY KEY (TREATMENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);